### PR TITLE
replace oc with kubectl

### PR DESCRIPTION
**Pull request by louiseohalloran**
replace oc with kubectl as it is erroring out in non OCP envs

### CODE REVIEW

**Comment by louiseohalloran** [comment]
https://github.com/ibm-apiconnect/v10-postmortem/issues/65

**Comment by louiseohalloran** [comment]
@geraintwjones any chance you can merge this - I do not seem to have access -we keep getting pmrs on this.

**Review by geraintwjones — APPROVED** [review]
Looks good to me.

**Comment by geraintwjones** [comment]
@louiseohalloran Done.

**Comment by louiseohalloran** [comment]
Thanks @geraintwjones

**Pull request merged**
